name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - personal
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
        env:
          VERSION: latest
      - name: Push
        run: make push
        env:
          VERSION: latest
      - name: Test
        run: make test
      - name: Lint
        run: make lint
